### ISSUE TITLE
Generalizing the course

### ISSUE THREAD

**Issue by eemilhaa** [GispoCoding/python-gis-training#3]
This issue collects the steps needed to make this course more generally applicable.

```[tasklist]
### Tasks
- [ ] Add course pages to the [course site repo](github.com/gispocoding/master-training-data). As most of this course is implemented as notebooks, only the contents of `ohjeet/` need to be considered here.
- [ ] Update the [course environment instructions](https://github.com/GispoCoding/python-gis-training/blob/main/ohjeet/kurssiymparisto.md) to be more general.
- [ ] Consider platforms other than Windows for local setup. Linux, macOS.
- [ ] Consider having the option of hosting python + jupyterlab elsewhere, mitigating all need for local installations.
```
